# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tem_value', models.CharField(max_length=250)),
                ('hum_value', models.CharField(max_length=250)),
                ('soil_value', models.CharField(max_length=250)),
                ('water_level', models.CharField(max_length=250)),
            ],
        ),
    ]
