# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_auto_20171011_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='watersensor',
            field=models.CharField(default=56, max_length=250),
            preserve_default=False,
        ),
    ]
