# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0005_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensor_read',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tem_value', models.CharField(max_length=250)),
                ('watersensor', models.CharField(max_length=250)),
                ('hum_value', models.CharField(max_length=250)),
                ('soil_value', models.CharField(max_length=250)),
                ('water_level', models.CharField(max_length=250)),
                ('timeanddate', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='humidity',
        ),
        migrations.DeleteModel(
            name='soilmoisture',
        ),
        migrations.DeleteModel(
            name='temperature',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='waterlevel',
        ),
    ]
