# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0007_auto_20171102_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='latitude',
            field=models.CharField(default=13.5515, max_length=250),
        ),
        migrations.AlterField(
            model_name='plant',
            name='longitude',
            field=models.CharField(default=79.9954, max_length=250),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_id',
            field=models.IntegerField(default=0),
        ),
    ]
