# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0008_auto_20171103_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor_read',
            name='condition',
            field=models.CharField(default='Hai', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensor_read',
            name='hum_value',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='sensor_read',
            name='soil_value',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='sensor_read',
            name='tem_value',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='sensor_read',
            name='timeanddate',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='sensor_read',
            name='water_level',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='sensor_read',
            name='watersensor',
            field=models.CharField(default=0, max_length=250),
        ),
    ]
