# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0009_auto_20171103_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='plant_name',
            field=models.CharField(default='tulasi', max_length=250),
        ),
    ]
